### ISSUE TITLE
Unable to run link-warden through docker-compose

### ISSUE THREAD

**Issue by nevertomorrow** [Daniel31x13/link-warden#13]
I followed the steps from README.md and tried to run it through `docker-compose` 
The only thing I modified in `docker-compose.yml` is 
```
    ports:
      - 13000:3000
 ```
as I have another app using `3000` port

Once it's up, I can see `link-warden` and `link-warden-api` keep restarting
```
docker ps | grep link-warden
19f293c1d366   link-warden_link-warden        "docker-entrypoint.s…"   35 seconds ago       Restarting (127) 4 seconds ago                                                                                                                                                                               link-warden_link-warden_1
a75e107d1c1b   link-warden_link-warden-api    "docker-entrypoint.s…"   About a minute ago   Restarting (1) 8 seconds ago                                                                                                                                                                                 link-warden_link-warden-api_1
58b51a340f39   mongo                          "docker-entrypoint.s…"   About a minute ago   Up About a minute                0.0.0.0:27017->27017/tcp, :::27017->27017/tcp                                                                                                                               link-warden_mongo_1
```

By checking the logs:
### api docker log
```
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/node/server.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/node/server.js' ]
}

Node.js v18.4.0
node:internal/modules/cjs/loader:949

  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/node/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/node/server.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/node/server.js' ]
}
```

### link-warden log
```

> link-warden@0.1.0 go
> react-scripts start

/tmp/go65699788867.sh: line 2: react-scripts: not found
```

Did I miss anything to config? 

Thanks

**Comment by axsddlr** [comment]
+1 to this

**Comment by Daniel31x13** [comment]
Hello,
Gonna get to it ASAP.

**Comment by burkely-00orso69** [comment]
same unfotunately...

**Comment by moeenaslam** [comment]
You have to run it with `docker compose` instead of `docker-compose`. To run, use `docker compose up`.
This project uses docker compose V2 and I can say that if you execute `docker-compose -v`, it will show you version 1.xx.xx whereas now docker comes with compose v2.

**Comment by Daniel31x13** [comment]
Hello @nevertomorrow,
Sorry to be unresponsive.
I applied the changes.

**Comment by melyux** [comment]
Got this error and never got the project running. Using docker compose v2. Tried deleting the images and the git folder and trying again, with no luck.
